#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 9

enum {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_COMMA = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_return = 8,
  anon_sym_let = 9,
  anon_sym_EQ = 10,
  anon_sym_if = 11,
  anon_sym_else = 12,
  anon_sym_BANG = 13,
  anon_sym_DASH = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT = 19,
  anon_sym_LT = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  anon_sym_PLUS = 23,
  anon_sym_fn = 24,
  sym_integer = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_string_token1 = 27,
  sym_true = 28,
  sym_false = 29,
  sym_program = 30,
  sym__statements = 31,
  sym_expression_statement = 32,
  sym__parameters = 33,
  sym_parameters = 34,
  sym_arguments = 35,
  sym_block_statement = 36,
  sym_return_statement = 37,
  sym_assignment = 38,
  sym__expression = 39,
  sym_if_expression = 40,
  sym_prefix_expression = 41,
  sym_infix_expression = 42,
  sym_grouped_expression = 43,
  sym_call = 44,
  sym_function_literal = 45,
  sym_string = 46,
  aux_sym_program_repeat1 = 47,
  aux_sym__parameters_repeat1 = 48,
  aux_sym_string_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_fn] = "fn",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_program] = "program",
  [sym__statements] = "_statements",
  [sym_expression_statement] = "expression_statement",
  [sym__parameters] = "_parameters",
  [sym_parameters] = "parameters",
  [sym_arguments] = "arguments",
  [sym_block_statement] = "block_statement",
  [sym_return_statement] = "return_statement",
  [sym_assignment] = "assignment",
  [sym__expression] = "_expression",
  [sym_if_expression] = "if_expression",
  [sym_prefix_expression] = "prefix_expression",
  [sym_infix_expression] = "infix_expression",
  [sym_grouped_expression] = "grouped_expression",
  [sym_call] = "call",
  [sym_function_literal] = "function_literal",
  [sym_string] = "string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_fn] = anon_sym_fn,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_program] = sym_program,
  [sym__statements] = sym__statements,
  [sym_expression_statement] = sym_expression_statement,
  [sym__parameters] = sym__parameters,
  [sym_parameters] = sym_parameters,
  [sym_arguments] = sym_arguments,
  [sym_block_statement] = sym_block_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_assignment] = sym_assignment,
  [sym__expression] = sym__expression,
  [sym_if_expression] = sym_if_expression,
  [sym_prefix_expression] = sym_prefix_expression,
  [sym_infix_expression] = sym_infix_expression,
  [sym_grouped_expression] = sym_grouped_expression,
  [sym_call] = sym_call,
  [sym_function_literal] = sym_function_literal,
  [sym_string] = sym_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_argument = 2,
  field_arguments = 3,
  field_body = 4,
  field_condition = 5,
  field_consequence = 6,
  field_function = 7,
  field_left = 8,
  field_operator = 9,
  field_parameters = 10,
  field_right = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_argument] = "argument",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 2},
  [8] = {.index = 15, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 1},
    {field_operator, 0},
  [2] =
    {field_arguments, 1},
    {field_function, 0},
  [4] =
    {field_condition, 1},
    {field_consequence, 2},
  [6] =
    {field_body, 2},
    {field_parameters, 1},
  [8] =
    {field_left, 0},
    {field_right, 2},
  [10] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [13] =
    {field_left, 1},
    {field_right, 3},
  [15] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == ';') ADVANCE(3);
      if (lookahead == '<') ADVANCE(17);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(57),
    [sym__statements] = STATE(21),
    [sym_expression_statement] = STATE(40),
    [sym_return_statement] = STATE(40),
    [sym_assignment] = STATE(40),
    [sym__expression] = STATE(26),
    [sym_if_expression] = STATE(26),
    [sym_prefix_expression] = STATE(26),
    [sym_infix_expression] = STATE(26),
    [sym_grouped_expression] = STATE(26),
    [sym_call] = STATE(26),
    [sym_function_literal] = STATE(26),
    [sym_string] = STATE(26),
    [aux_sym_program_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [sym_integer] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_true] = ACTIONS(23),
    [sym_false] = ACTIONS(23),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_if] = ACTIONS(27),
    [anon_sym_else] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_fn] = ACTIONS(27),
    [sym_integer] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_true] = ACTIONS(27),
    [sym_false] = ACTIONS(27),
  },
  [3] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_return] = ACTIONS(33),
    [anon_sym_let] = ACTIONS(33),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_else] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_BANG_EQ] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_fn] = ACTIONS(33),
    [sym_integer] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [sym_true] = ACTIONS(33),
    [sym_false] = ACTIONS(33),
  },
  [4] = {
    [sym_arguments] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_return] = ACTIONS(37),
    [anon_sym_let] = ACTIONS(37),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_BANG] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(35),
    [anon_sym_BANG_EQ] = ACTIONS(35),
    [anon_sym_GT_EQ] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_fn] = ACTIONS(37),
    [sym_integer] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_true] = ACTIONS(37),
    [sym_false] = ACTIONS(37),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_identifier] = ACTIONS(43),
    [anon_sym_SEMI] = ACTIONS(41),
    [anon_sym_COMMA] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_return] = ACTIONS(43),
    [anon_sym_let] = ACTIONS(43),
    [anon_sym_if] = ACTIONS(43),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_BANG_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_fn] = ACTIONS(43),
    [sym_integer] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [sym_true] = ACTIONS(43),
    [sym_false] = ACTIONS(43),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_SEMI] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_return] = ACTIONS(47),
    [anon_sym_let] = ACTIONS(47),
    [anon_sym_if] = ACTIONS(47),
    [anon_sym_else] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_fn] = ACTIONS(47),
    [sym_integer] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [sym_true] = ACTIONS(47),
    [sym_false] = ACTIONS(47),
  },
  [7] = {
    [sym__statements] = STATE(7),
    [sym_expression_statement] = STATE(40),
    [sym_return_statement] = STATE(40),
    [sym_assignment] = STATE(40),
    [sym__expression] = STATE(26),
    [sym_if_expression] = STATE(26),
    [sym_prefix_expression] = STATE(26),
    [sym_infix_expression] = STATE(26),
    [sym_grouped_expression] = STATE(26),
    [sym_call] = STATE(26),
    [sym_function_literal] = STATE(26),
    [sym_string] = STATE(26),
    [aux_sym_program_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(54),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_return] = ACTIONS(57),
    [anon_sym_let] = ACTIONS(60),
    [anon_sym_if] = ACTIONS(63),
    [anon_sym_BANG] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_fn] = ACTIONS(69),
    [sym_integer] = ACTIONS(72),
    [anon_sym_DQUOTE] = ACTIONS(75),
    [sym_true] = ACTIONS(78),
    [sym_false] = ACTIONS(78),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_return] = ACTIONS(83),
    [anon_sym_let] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_BANG] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(81),
    [anon_sym_SLASH] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_fn] = ACTIONS(83),
    [sym_integer] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_true] = ACTIONS(83),
    [sym_false] = ACTIONS(83),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_return] = ACTIONS(83),
    [anon_sym_let] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_BANG] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_fn] = ACTIONS(83),
    [sym_integer] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_true] = ACTIONS(83),
    [sym_false] = ACTIONS(83),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_return] = ACTIONS(83),
    [anon_sym_let] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_BANG] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_fn] = ACTIONS(83),
    [sym_integer] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_true] = ACTIONS(83),
    [sym_false] = ACTIONS(83),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_return] = ACTIONS(83),
    [anon_sym_let] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_BANG] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_fn] = ACTIONS(83),
    [sym_integer] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(81),
    [sym_true] = ACTIONS(83),
    [sym_false] = ACTIONS(83),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_identifier] = ACTIONS(95),
    [anon_sym_SEMI] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_return] = ACTIONS(95),
    [anon_sym_let] = ACTIONS(95),
    [anon_sym_if] = ACTIONS(95),
    [anon_sym_BANG] = ACTIONS(95),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_EQ_EQ] = ACTIONS(93),
    [anon_sym_BANG_EQ] = ACTIONS(93),
    [anon_sym_GT_EQ] = ACTIONS(93),
    [anon_sym_LT_EQ] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(95),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_SLASH] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_fn] = ACTIONS(95),
    [sym_integer] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(93),
    [sym_true] = ACTIONS(95),
    [sym_false] = ACTIONS(95),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_identifier] = ACTIONS(99),
    [anon_sym_SEMI] = ACTIONS(97),
    [anon_sym_COMMA] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_RPAREN] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_return] = ACTIONS(99),
    [anon_sym_let] = ACTIONS(99),
    [anon_sym_if] = ACTIONS(99),
    [anon_sym_BANG] = ACTIONS(99),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_EQ_EQ] = ACTIONS(97),
    [anon_sym_BANG_EQ] = ACTIONS(97),
    [anon_sym_GT_EQ] = ACTIONS(97),
    [anon_sym_LT_EQ] = ACTIONS(97),
    [anon_sym_GT] = ACTIONS(99),
    [anon_sym_LT] = ACTIONS(99),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_SLASH] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_fn] = ACTIONS(99),
    [sym_integer] = ACTIONS(97),
    [anon_sym_DQUOTE] = ACTIONS(97),
    [sym_true] = ACTIONS(99),
    [sym_false] = ACTIONS(99),
  },
  [14] = {
    [sym_arguments] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_return] = ACTIONS(37),
    [anon_sym_let] = ACTIONS(37),
    [anon_sym_EQ] = ACTIONS(101),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_BANG] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(35),
    [anon_sym_BANG_EQ] = ACTIONS(35),
    [anon_sym_GT_EQ] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_fn] = ACTIONS(37),
    [sym_integer] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_true] = ACTIONS(37),
    [sym_false] = ACTIONS(37),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(103),
    [sym_identifier] = ACTIONS(105),
    [anon_sym_SEMI] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_return] = ACTIONS(105),
    [anon_sym_let] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(105),
    [anon_sym_BANG] = ACTIONS(105),
    [anon_sym_DASH] = ACTIONS(103),
    [anon_sym_EQ_EQ] = ACTIONS(103),
    [anon_sym_BANG_EQ] = ACTIONS(103),
    [anon_sym_GT_EQ] = ACTIONS(103),
    [anon_sym_LT_EQ] = ACTIONS(103),
    [anon_sym_GT] = ACTIONS(105),
    [anon_sym_LT] = ACTIONS(105),
    [anon_sym_STAR] = ACTIONS(103),
    [anon_sym_SLASH] = ACTIONS(103),
    [anon_sym_PLUS] = ACTIONS(103),
    [anon_sym_fn] = ACTIONS(105),
    [sym_integer] = ACTIONS(103),
    [anon_sym_DQUOTE] = ACTIONS(103),
    [sym_true] = ACTIONS(105),
    [sym_false] = ACTIONS(105),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym_identifier] = ACTIONS(109),
    [anon_sym_SEMI] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(107),
    [anon_sym_LPAREN] = ACTIONS(107),
    [anon_sym_RPAREN] = ACTIONS(107),
    [anon_sym_RBRACE] = ACTIONS(107),
    [anon_sym_return] = ACTIONS(109),
    [anon_sym_let] = ACTIONS(109),
    [anon_sym_if] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(107),
    [anon_sym_EQ_EQ] = ACTIONS(107),
    [anon_sym_BANG_EQ] = ACTIONS(107),
    [anon_sym_GT_EQ] = ACTIONS(107),
    [anon_sym_LT_EQ] = ACTIONS(107),
    [anon_sym_GT] = ACTIONS(109),
    [anon_sym_LT] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(107),
    [anon_sym_SLASH] = ACTIONS(107),
    [anon_sym_PLUS] = ACTIONS(107),
    [anon_sym_fn] = ACTIONS(109),
    [sym_integer] = ACTIONS(107),
    [anon_sym_DQUOTE] = ACTIONS(107),
    [sym_true] = ACTIONS(109),
    [sym_false] = ACTIONS(109),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym_identifier] = ACTIONS(113),
    [anon_sym_SEMI] = ACTIONS(111),
    [anon_sym_COMMA] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(111),
    [anon_sym_RPAREN] = ACTIONS(111),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_return] = ACTIONS(113),
    [anon_sym_let] = ACTIONS(113),
    [anon_sym_if] = ACTIONS(113),
    [anon_sym_BANG] = ACTIONS(113),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym_EQ_EQ] = ACTIONS(111),
    [anon_sym_BANG_EQ] = ACTIONS(111),
    [anon_sym_GT_EQ] = ACTIONS(111),
    [anon_sym_LT_EQ] = ACTIONS(111),
    [anon_sym_GT] = ACTIONS(113),
    [anon_sym_LT] = ACTIONS(113),
    [anon_sym_STAR] = ACTIONS(111),
    [anon_sym_SLASH] = ACTIONS(111),
    [anon_sym_PLUS] = ACTIONS(111),
    [anon_sym_fn] = ACTIONS(113),
    [sym_integer] = ACTIONS(111),
    [anon_sym_DQUOTE] = ACTIONS(111),
    [sym_true] = ACTIONS(113),
    [sym_false] = ACTIONS(113),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym_identifier] = ACTIONS(117),
    [anon_sym_SEMI] = ACTIONS(115),
    [anon_sym_COMMA] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(115),
    [anon_sym_RPAREN] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_return] = ACTIONS(117),
    [anon_sym_let] = ACTIONS(117),
    [anon_sym_if] = ACTIONS(117),
    [anon_sym_BANG] = ACTIONS(117),
    [anon_sym_DASH] = ACTIONS(115),
    [anon_sym_EQ_EQ] = ACTIONS(115),
    [anon_sym_BANG_EQ] = ACTIONS(115),
    [anon_sym_GT_EQ] = ACTIONS(115),
    [anon_sym_LT_EQ] = ACTIONS(115),
    [anon_sym_GT] = ACTIONS(117),
    [anon_sym_LT] = ACTIONS(117),
    [anon_sym_STAR] = ACTIONS(115),
    [anon_sym_SLASH] = ACTIONS(115),
    [anon_sym_PLUS] = ACTIONS(115),
    [anon_sym_fn] = ACTIONS(117),
    [sym_integer] = ACTIONS(115),
    [anon_sym_DQUOTE] = ACTIONS(115),
    [sym_true] = ACTIONS(117),
    [sym_false] = ACTIONS(117),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(119),
    [sym_identifier] = ACTIONS(121),
    [anon_sym_SEMI] = ACTIONS(119),
    [anon_sym_COMMA] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_RPAREN] = ACTIONS(119),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_return] = ACTIONS(121),
    [anon_sym_let] = ACTIONS(121),
    [anon_sym_if] = ACTIONS(121),
    [anon_sym_BANG] = ACTIONS(121),
    [anon_sym_DASH] = ACTIONS(119),
    [anon_sym_EQ_EQ] = ACTIONS(119),
    [anon_sym_BANG_EQ] = ACTIONS(119),
    [anon_sym_GT_EQ] = ACTIONS(119),
    [anon_sym_LT_EQ] = ACTIONS(119),
    [anon_sym_GT] = ACTIONS(121),
    [anon_sym_LT] = ACTIONS(121),
    [anon_sym_STAR] = ACTIONS(119),
    [anon_sym_SLASH] = ACTIONS(119),
    [anon_sym_PLUS] = ACTIONS(119),
    [anon_sym_fn] = ACTIONS(121),
    [sym_integer] = ACTIONS(119),
    [anon_sym_DQUOTE] = ACTIONS(119),
    [sym_true] = ACTIONS(121),
    [sym_false] = ACTIONS(121),
  },
  [20] = {
    [sym__statements] = STATE(22),
    [sym_expression_statement] = STATE(40),
    [sym_return_statement] = STATE(40),
    [sym_assignment] = STATE(40),
    [sym__expression] = STATE(26),
    [sym_if_expression] = STATE(26),
    [sym_prefix_expression] = STATE(26),
    [sym_infix_expression] = STATE(26),
    [sym_grouped_expression] = STATE(26),
    [sym_call] = STATE(26),
    [sym_function_literal] = STATE(26),
    [sym_string] = STATE(26),
    [aux_sym_program_repeat1] = STATE(22),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(123),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [sym_integer] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_true] = ACTIONS(23),
    [sym_false] = ACTIONS(23),
  },
  [21] = {
    [sym__statements] = STATE(7),
    [sym_expression_statement] = STATE(40),
    [sym_return_statement] = STATE(40),
    [sym_assignment] = STATE(40),
    [sym__expression] = STATE(26),
    [sym_if_expression] = STATE(26),
    [sym_prefix_expression] = STATE(26),
    [sym_infix_expression] = STATE(26),
    [sym_grouped_expression] = STATE(26),
    [sym_call] = STATE(26),
    [sym_function_literal] = STATE(26),
    [sym_string] = STATE(26),
    [aux_sym_program_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(125),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [sym_integer] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_true] = ACTIONS(23),
    [sym_false] = ACTIONS(23),
  },
  [22] = {
    [sym__statements] = STATE(7),
    [sym_expression_statement] = STATE(40),
    [sym_return_statement] = STATE(40),
    [sym_assignment] = STATE(40),
    [sym__expression] = STATE(26),
    [sym_if_expression] = STATE(26),
    [sym_prefix_expression] = STATE(26),
    [sym_infix_expression] = STATE(26),
    [sym_grouped_expression] = STATE(26),
    [sym_call] = STATE(26),
    [sym_function_literal] = STATE(26),
    [sym_string] = STATE(26),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(127),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [sym_integer] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_true] = ACTIONS(23),
    [sym_false] = ACTIONS(23),
  },
  [23] = {
    [ts_builtin_sym_end] = ACTIONS(129),
    [sym_identifier] = ACTIONS(131),
    [anon_sym_SEMI] = ACTIONS(129),
    [anon_sym_COMMA] = ACTIONS(129),
    [anon_sym_LPAREN] = ACTIONS(129),
    [anon_sym_RPAREN] = ACTIONS(129),
    [anon_sym_RBRACE] = ACTIONS(129),
    [anon_sym_return] = ACTIONS(131),
    [anon_sym_let] = ACTIONS(131),
    [anon_sym_if] = ACTIONS(131),
    [anon_sym_BANG] = ACTIONS(131),
    [anon_sym_DASH] = ACTIONS(129),
    [anon_sym_EQ_EQ] = ACTIONS(129),
    [anon_sym_BANG_EQ] = ACTIONS(129),
    [anon_sym_GT_EQ] = ACTIONS(129),
    [anon_sym_LT_EQ] = ACTIONS(129),
    [anon_sym_GT] = ACTIONS(131),
    [anon_sym_LT] = ACTIONS(131),
    [anon_sym_STAR] = ACTIONS(129),
    [anon_sym_SLASH] = ACTIONS(129),
    [anon_sym_PLUS] = ACTIONS(129),
    [anon_sym_fn] = ACTIONS(131),
    [sym_integer] = ACTIONS(129),
    [anon_sym_DQUOTE] = ACTIONS(129),
    [sym_true] = ACTIONS(131),
    [sym_false] = ACTIONS(131),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(135), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [39] = 7,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(141), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [78] = 7,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(143), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(145), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [117] = 7,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(147), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(149), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [156] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(157), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(155), 2,
      anon_sym_return,
      anon_sym_let,
    ACTIONS(159), 2,
      sym_true,
      sym_false,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(24), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [202] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 1,
      sym_integer,
    STATE(56), 1,
      sym__parameters,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(165), 2,
      sym_true,
      sym_false,
    STATE(42), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [245] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(163), 1,
      sym_integer,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      sym__parameters,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(165), 2,
      sym_true,
      sym_false,
    STATE(42), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [288] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(169), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(171), 2,
      sym_true,
      sym_false,
    STATE(25), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [325] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(173), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(175), 2,
      sym_true,
      sym_false,
    STATE(10), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [362] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(177), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(179), 2,
      sym_true,
      sym_false,
    STATE(8), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [399] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(181), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(183), 2,
      sym_true,
      sym_false,
    STATE(44), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [436] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(187), 2,
      sym_true,
      sym_false,
    STATE(27), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [473] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(191), 2,
      sym_true,
      sym_false,
    STATE(43), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [510] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(193), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(195), 2,
      sym_true,
      sym_false,
    STATE(19), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [547] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(199), 2,
      sym_true,
      sym_false,
    STATE(9), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [584] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(201), 1,
      sym_integer,
    ACTIONS(15), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(203), 2,
      sym_true,
      sym_false,
    STATE(11), 8,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_function_literal,
      sym_string,
  [621] = 3,
    ACTIONS(209), 1,
      anon_sym_SEMI,
    ACTIONS(205), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(207), 7,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [643] = 2,
    ACTIONS(211), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(213), 7,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [662] = 8,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym__parameters_repeat1,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [692] = 6,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(219), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [717] = 6,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(85), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(91), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(137), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [741] = 3,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    ACTIONS(225), 1,
      aux_sym_string_token1,
    STATE(46), 1,
      aux_sym_string_repeat1,
  [751] = 3,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    ACTIONS(229), 1,
      aux_sym_string_token1,
    STATE(46), 1,
      aux_sym_string_repeat1,
  [761] = 3,
    ACTIONS(232), 1,
      anon_sym_DQUOTE,
    ACTIONS(234), 1,
      aux_sym_string_token1,
    STATE(45), 1,
      aux_sym_string_repeat1,
  [771] = 3,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym__parameters_repeat1,
  [781] = 3,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym__parameters_repeat1,
  [791] = 2,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block_statement,
  [798] = 2,
    ACTIONS(243), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_parameters,
  [805] = 2,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym_block_statement,
  [812] = 2,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_block_statement,
  [819] = 2,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_grouped_expression,
  [826] = 1,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [830] = 1,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
  [834] = 1,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [838] = 1,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
  [842] = 1,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
  [846] = 1,
    ACTIONS(255), 1,
      sym_identifier,
  [850] = 1,
    ACTIONS(257), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 39,
  [SMALL_STATE(26)] = 78,
  [SMALL_STATE(27)] = 117,
  [SMALL_STATE(28)] = 156,
  [SMALL_STATE(29)] = 202,
  [SMALL_STATE(30)] = 245,
  [SMALL_STATE(31)] = 288,
  [SMALL_STATE(32)] = 325,
  [SMALL_STATE(33)] = 362,
  [SMALL_STATE(34)] = 399,
  [SMALL_STATE(35)] = 436,
  [SMALL_STATE(36)] = 473,
  [SMALL_STATE(37)] = 510,
  [SMALL_STATE(38)] = 547,
  [SMALL_STATE(39)] = 584,
  [SMALL_STATE(40)] = 621,
  [SMALL_STATE(41)] = 643,
  [SMALL_STATE(42)] = 662,
  [SMALL_STATE(43)] = 692,
  [SMALL_STATE(44)] = 717,
  [SMALL_STATE(45)] = 741,
  [SMALL_STATE(46)] = 751,
  [SMALL_STATE(47)] = 761,
  [SMALL_STATE(48)] = 771,
  [SMALL_STATE(49)] = 781,
  [SMALL_STATE(50)] = 791,
  [SMALL_STATE(51)] = 798,
  [SMALL_STATE(52)] = 805,
  [SMALL_STATE(53)] = 812,
  [SMALL_STATE(54)] = 819,
  [SMALL_STATE(55)] = 826,
  [SMALL_STATE(56)] = 830,
  [SMALL_STATE(57)] = 834,
  [SMALL_STATE(58)] = 838,
  [SMALL_STATE(59)] = 842,
  [SMALL_STATE(60)] = 846,
  [SMALL_STATE(61)] = 850,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3, .production_id = 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3, .production_id = 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expression, 3),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expression, 3),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(14),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(34),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(28),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(60),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(54),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(37),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(51),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(26),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(47),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(26),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expression, 3, .production_id = 6),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_expression, 3, .production_id = 6),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, .production_id = 8),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, .production_id = 8),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 3, .production_id = 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 3, .production_id = 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expression, 2, .production_id = 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expression, 2, .production_id = 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, .production_id = 7),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, .production_id = 7),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 5),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, .production_id = 5),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statements, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 2),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statements, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(46),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2), SHIFT_REPEAT(36),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [249] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
