#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 30
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 12

enum {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_COMMA = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_COLON = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_return = 11,
  anon_sym_let = 12,
  anon_sym_EQ = 13,
  anon_sym_if = 14,
  anon_sym_else = 15,
  anon_sym_BANG = 16,
  anon_sym_DASH = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_BANG_EQ = 19,
  anon_sym_GT_EQ = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_GT = 22,
  anon_sym_LT = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_PLUS = 26,
  anon_sym_fn = 27,
  sym_integer = 28,
  anon_sym_DQUOTE = 29,
  aux_sym_string_token1 = 30,
  sym_true = 31,
  sym_false = 32,
  sym_program = 33,
  sym__statements = 34,
  sym_expression_statement = 35,
  sym__parameters = 36,
  sym_parameters = 37,
  sym_arguments = 38,
  sym_elements = 39,
  sym_pair = 40,
  sym_block_statement = 41,
  sym_return_statement = 42,
  sym_assignment = 43,
  sym__expression = 44,
  sym_if_expression = 45,
  sym_prefix_expression = 46,
  sym_infix_expression = 47,
  sym_grouped_expression = 48,
  sym_call = 49,
  sym_index_expression = 50,
  sym_function_literal = 51,
  sym_string = 52,
  sym_array = 53,
  sym_hash = 54,
  aux_sym_program_repeat1 = 55,
  aux_sym__parameters_repeat1 = 56,
  aux_sym_string_repeat1 = 57,
  aux_sym_hash_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_return] = "return",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_fn] = "fn",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_program] = "program",
  [sym__statements] = "_statements",
  [sym_expression_statement] = "expression_statement",
  [sym__parameters] = "_parameters",
  [sym_parameters] = "parameters",
  [sym_arguments] = "arguments",
  [sym_elements] = "elements",
  [sym_pair] = "pair",
  [sym_block_statement] = "block_statement",
  [sym_return_statement] = "return_statement",
  [sym_assignment] = "assignment",
  [sym__expression] = "_expression",
  [sym_if_expression] = "if_expression",
  [sym_prefix_expression] = "prefix_expression",
  [sym_infix_expression] = "infix_expression",
  [sym_grouped_expression] = "grouped_expression",
  [sym_call] = "call",
  [sym_index_expression] = "index_expression",
  [sym_function_literal] = "function_literal",
  [sym_string] = "string",
  [sym_array] = "array",
  [sym_hash] = "hash",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_hash_repeat1] = "hash_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_fn] = anon_sym_fn,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_program] = sym_program,
  [sym__statements] = sym__statements,
  [sym_expression_statement] = sym_expression_statement,
  [sym__parameters] = sym__parameters,
  [sym_parameters] = sym_parameters,
  [sym_arguments] = sym_arguments,
  [sym_elements] = sym_elements,
  [sym_pair] = sym_pair,
  [sym_block_statement] = sym_block_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_assignment] = sym_assignment,
  [sym__expression] = sym__expression,
  [sym_if_expression] = sym_if_expression,
  [sym_prefix_expression] = sym_prefix_expression,
  [sym_infix_expression] = sym_infix_expression,
  [sym_grouped_expression] = sym_grouped_expression,
  [sym_call] = sym_call,
  [sym_index_expression] = sym_index_expression,
  [sym_function_literal] = sym_function_literal,
  [sym_string] = sym_string,
  [sym_array] = sym_array,
  [sym_hash] = sym_hash,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_hash_repeat1] = aux_sym_hash_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_elements] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_index_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_hash] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hash_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_argument = 2,
  field_arguments = 3,
  field_body = 4,
  field_condition = 5,
  field_consequence = 6,
  field_elements = 7,
  field_function = 8,
  field_index = 9,
  field_key = 10,
  field_left = 11,
  field_operator = 12,
  field_parameters = 13,
  field_right = 14,
  field_value = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_argument] = "argument",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_elements] = "elements",
  [field_function] = "function",
  [field_index] = "index",
  [field_key] = "key",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 2},
  [9] = {.index = 16, .length = 2},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_elements, 0},
  [1] =
    {field_argument, 1},
    {field_operator, 0},
  [3] =
    {field_arguments, 1},
    {field_function, 0},
  [5] =
    {field_condition, 1},
    {field_consequence, 2},
  [7] =
    {field_body, 2},
    {field_parameters, 1},
  [9] =
    {field_left, 0},
    {field_right, 2},
  [11] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [14] =
    {field_key, 0},
    {field_value, 2},
  [16] =
    {field_left, 1},
    {field_right, 3},
  [18] =
    {field_index, 2},
    {field_left, 0},
  [20] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '!') ADVANCE(13);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == ';') ADVANCE(3);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '=') ADVANCE(12);
      if (lookahead == '>') ADVANCE(19);
      if (lookahead == '[') ADVANCE(7);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(79),
    [sym__statements] = STATE(4),
    [sym_expression_statement] = STATE(52),
    [sym_elements] = STATE(16),
    [sym_return_statement] = STATE(52),
    [sym_assignment] = STATE(52),
    [sym__expression] = STATE(37),
    [sym_if_expression] = STATE(37),
    [sym_prefix_expression] = STATE(37),
    [sym_infix_expression] = STATE(37),
    [sym_grouped_expression] = STATE(37),
    [sym_call] = STATE(37),
    [sym_index_expression] = STATE(37),
    [sym_function_literal] = STATE(37),
    [sym_string] = STATE(37),
    [sym_array] = STATE(37),
    [sym_hash] = STATE(37),
    [aux_sym_program_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_true] = ACTIONS(27),
    [sym_false] = ACTIONS(27),
  },
  [2] = {
    [sym__statements] = STATE(2),
    [sym_expression_statement] = STATE(52),
    [sym_elements] = STATE(16),
    [sym_return_statement] = STATE(52),
    [sym_assignment] = STATE(52),
    [sym__expression] = STATE(37),
    [sym_if_expression] = STATE(37),
    [sym_prefix_expression] = STATE(37),
    [sym_infix_expression] = STATE(37),
    [sym_grouped_expression] = STATE(37),
    [sym_call] = STATE(37),
    [sym_index_expression] = STATE(37),
    [sym_function_literal] = STATE(37),
    [sym_string] = STATE(37),
    [sym_array] = STATE(37),
    [sym_hash] = STATE(37),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(34),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(40),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_return] = ACTIONS(43),
    [anon_sym_let] = ACTIONS(46),
    [anon_sym_if] = ACTIONS(49),
    [anon_sym_BANG] = ACTIONS(52),
    [anon_sym_DASH] = ACTIONS(52),
    [anon_sym_fn] = ACTIONS(55),
    [sym_integer] = ACTIONS(58),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [sym_true] = ACTIONS(64),
    [sym_false] = ACTIONS(64),
  },
  [3] = {
    [sym__statements] = STATE(5),
    [sym_expression_statement] = STATE(52),
    [sym_elements] = STATE(16),
    [sym_return_statement] = STATE(52),
    [sym_assignment] = STATE(52),
    [sym__expression] = STATE(37),
    [sym_if_expression] = STATE(37),
    [sym_prefix_expression] = STATE(37),
    [sym_infix_expression] = STATE(37),
    [sym_grouped_expression] = STATE(37),
    [sym_call] = STATE(37),
    [sym_index_expression] = STATE(37),
    [sym_function_literal] = STATE(37),
    [sym_string] = STATE(37),
    [sym_array] = STATE(37),
    [sym_hash] = STATE(37),
    [aux_sym_program_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(67),
    [anon_sym_return] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_true] = ACTIONS(27),
    [sym_false] = ACTIONS(27),
  },
  [4] = {
    [sym__statements] = STATE(2),
    [sym_expression_statement] = STATE(52),
    [sym_elements] = STATE(16),
    [sym_return_statement] = STATE(52),
    [sym_assignment] = STATE(52),
    [sym__expression] = STATE(37),
    [sym_if_expression] = STATE(37),
    [sym_prefix_expression] = STATE(37),
    [sym_infix_expression] = STATE(37),
    [sym_grouped_expression] = STATE(37),
    [sym_call] = STATE(37),
    [sym_index_expression] = STATE(37),
    [sym_function_literal] = STATE(37),
    [sym_string] = STATE(37),
    [sym_array] = STATE(37),
    [sym_hash] = STATE(37),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_return] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_true] = ACTIONS(27),
    [sym_false] = ACTIONS(27),
  },
  [5] = {
    [sym__statements] = STATE(2),
    [sym_expression_statement] = STATE(52),
    [sym_elements] = STATE(16),
    [sym_return_statement] = STATE(52),
    [sym_assignment] = STATE(52),
    [sym__expression] = STATE(37),
    [sym_if_expression] = STATE(37),
    [sym_prefix_expression] = STATE(37),
    [sym_infix_expression] = STATE(37),
    [sym_grouped_expression] = STATE(37),
    [sym_call] = STATE(37),
    [sym_index_expression] = STATE(37),
    [sym_function_literal] = STATE(37),
    [sym_string] = STATE(37),
    [sym_array] = STATE(37),
    [sym_hash] = STATE(37),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_return] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_true] = ACTIONS(27),
    [sym_false] = ACTIONS(27),
  },
  [6] = {
    [sym_arguments] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(73),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_COLON] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_return] = ACTIONS(75),
    [anon_sym_let] = ACTIONS(75),
    [anon_sym_if] = ACTIONS(75),
    [anon_sym_BANG] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(73),
    [anon_sym_BANG_EQ] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_fn] = ACTIONS(75),
    [sym_integer] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [sym_true] = ACTIONS(75),
    [sym_false] = ACTIONS(75),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [sym_identifier] = ACTIONS(81),
    [anon_sym_SEMI] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(79),
    [anon_sym_RBRACK] = ACTIONS(79),
    [anon_sym_COLON] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_return] = ACTIONS(81),
    [anon_sym_let] = ACTIONS(81),
    [anon_sym_if] = ACTIONS(81),
    [anon_sym_else] = ACTIONS(83),
    [anon_sym_BANG] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_EQ_EQ] = ACTIONS(79),
    [anon_sym_BANG_EQ] = ACTIONS(79),
    [anon_sym_GT_EQ] = ACTIONS(79),
    [anon_sym_LT_EQ] = ACTIONS(79),
    [anon_sym_GT] = ACTIONS(81),
    [anon_sym_LT] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_PLUS] = ACTIONS(79),
    [anon_sym_fn] = ACTIONS(81),
    [sym_integer] = ACTIONS(79),
    [anon_sym_DQUOTE] = ACTIONS(79),
    [sym_true] = ACTIONS(81),
    [sym_false] = ACTIONS(81),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(87),
    [anon_sym_SEMI] = ACTIONS(85),
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_COLON] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_return] = ACTIONS(87),
    [anon_sym_let] = ACTIONS(87),
    [anon_sym_if] = ACTIONS(87),
    [anon_sym_else] = ACTIONS(87),
    [anon_sym_BANG] = ACTIONS(87),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(85),
    [anon_sym_BANG_EQ] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_GT] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(87),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_fn] = ACTIONS(87),
    [sym_integer] = ACTIONS(85),
    [anon_sym_DQUOTE] = ACTIONS(85),
    [sym_true] = ACTIONS(87),
    [sym_false] = ACTIONS(87),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_identifier] = ACTIONS(91),
    [anon_sym_SEMI] = ACTIONS(89),
    [anon_sym_COMMA] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_RPAREN] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(89),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_COLON] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_return] = ACTIONS(91),
    [anon_sym_let] = ACTIONS(91),
    [anon_sym_if] = ACTIONS(91),
    [anon_sym_else] = ACTIONS(91),
    [anon_sym_BANG] = ACTIONS(91),
    [anon_sym_DASH] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_BANG_EQ] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(89),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_fn] = ACTIONS(91),
    [sym_integer] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [sym_true] = ACTIONS(91),
    [sym_false] = ACTIONS(91),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_identifier] = ACTIONS(95),
    [anon_sym_SEMI] = ACTIONS(93),
    [anon_sym_COMMA] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_RPAREN] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(93),
    [anon_sym_RBRACK] = ACTIONS(93),
    [anon_sym_COLON] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_return] = ACTIONS(95),
    [anon_sym_let] = ACTIONS(95),
    [anon_sym_if] = ACTIONS(95),
    [anon_sym_BANG] = ACTIONS(95),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_EQ_EQ] = ACTIONS(93),
    [anon_sym_BANG_EQ] = ACTIONS(93),
    [anon_sym_GT_EQ] = ACTIONS(93),
    [anon_sym_LT_EQ] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(95),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_SLASH] = ACTIONS(93),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_fn] = ACTIONS(95),
    [sym_integer] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(93),
    [sym_true] = ACTIONS(95),
    [sym_false] = ACTIONS(95),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_identifier] = ACTIONS(99),
    [anon_sym_SEMI] = ACTIONS(97),
    [anon_sym_COMMA] = ACTIONS(97),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_RPAREN] = ACTIONS(97),
    [anon_sym_LBRACK] = ACTIONS(97),
    [anon_sym_RBRACK] = ACTIONS(97),
    [anon_sym_COLON] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_return] = ACTIONS(99),
    [anon_sym_let] = ACTIONS(99),
    [anon_sym_if] = ACTIONS(99),
    [anon_sym_BANG] = ACTIONS(99),
    [anon_sym_DASH] = ACTIONS(97),
    [anon_sym_EQ_EQ] = ACTIONS(97),
    [anon_sym_BANG_EQ] = ACTIONS(97),
    [anon_sym_GT_EQ] = ACTIONS(97),
    [anon_sym_LT_EQ] = ACTIONS(97),
    [anon_sym_GT] = ACTIONS(99),
    [anon_sym_LT] = ACTIONS(99),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_SLASH] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_fn] = ACTIONS(99),
    [sym_integer] = ACTIONS(97),
    [anon_sym_DQUOTE] = ACTIONS(97),
    [sym_true] = ACTIONS(99),
    [sym_false] = ACTIONS(99),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_identifier] = ACTIONS(103),
    [anon_sym_SEMI] = ACTIONS(101),
    [anon_sym_COMMA] = ACTIONS(101),
    [anon_sym_LPAREN] = ACTIONS(101),
    [anon_sym_RPAREN] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(101),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_COLON] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_return] = ACTIONS(103),
    [anon_sym_let] = ACTIONS(103),
    [anon_sym_if] = ACTIONS(103),
    [anon_sym_BANG] = ACTIONS(103),
    [anon_sym_DASH] = ACTIONS(101),
    [anon_sym_EQ_EQ] = ACTIONS(101),
    [anon_sym_BANG_EQ] = ACTIONS(101),
    [anon_sym_GT_EQ] = ACTIONS(101),
    [anon_sym_LT_EQ] = ACTIONS(101),
    [anon_sym_GT] = ACTIONS(103),
    [anon_sym_LT] = ACTIONS(103),
    [anon_sym_STAR] = ACTIONS(101),
    [anon_sym_SLASH] = ACTIONS(101),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_fn] = ACTIONS(103),
    [sym_integer] = ACTIONS(101),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [sym_true] = ACTIONS(103),
    [sym_false] = ACTIONS(103),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_identifier] = ACTIONS(107),
    [anon_sym_SEMI] = ACTIONS(105),
    [anon_sym_COMMA] = ACTIONS(105),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_RPAREN] = ACTIONS(105),
    [anon_sym_LBRACK] = ACTIONS(105),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_COLON] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(105),
    [anon_sym_RBRACE] = ACTIONS(105),
    [anon_sym_return] = ACTIONS(107),
    [anon_sym_let] = ACTIONS(107),
    [anon_sym_if] = ACTIONS(107),
    [anon_sym_BANG] = ACTIONS(107),
    [anon_sym_DASH] = ACTIONS(105),
    [anon_sym_EQ_EQ] = ACTIONS(105),
    [anon_sym_BANG_EQ] = ACTIONS(105),
    [anon_sym_GT_EQ] = ACTIONS(105),
    [anon_sym_LT_EQ] = ACTIONS(105),
    [anon_sym_GT] = ACTIONS(107),
    [anon_sym_LT] = ACTIONS(107),
    [anon_sym_STAR] = ACTIONS(105),
    [anon_sym_SLASH] = ACTIONS(105),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_fn] = ACTIONS(107),
    [sym_integer] = ACTIONS(105),
    [anon_sym_DQUOTE] = ACTIONS(105),
    [sym_true] = ACTIONS(107),
    [sym_false] = ACTIONS(107),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_SEMI] = ACTIONS(109),
    [anon_sym_COMMA] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_RPAREN] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(109),
    [anon_sym_RBRACK] = ACTIONS(109),
    [anon_sym_COLON] = ACTIONS(109),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_return] = ACTIONS(111),
    [anon_sym_let] = ACTIONS(111),
    [anon_sym_if] = ACTIONS(111),
    [anon_sym_BANG] = ACTIONS(111),
    [anon_sym_DASH] = ACTIONS(109),
    [anon_sym_EQ_EQ] = ACTIONS(109),
    [anon_sym_BANG_EQ] = ACTIONS(109),
    [anon_sym_GT_EQ] = ACTIONS(109),
    [anon_sym_LT_EQ] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(111),
    [anon_sym_LT] = ACTIONS(111),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_fn] = ACTIONS(111),
    [sym_integer] = ACTIONS(109),
    [anon_sym_DQUOTE] = ACTIONS(109),
    [sym_true] = ACTIONS(111),
    [sym_false] = ACTIONS(111),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(113),
    [sym_identifier] = ACTIONS(115),
    [anon_sym_SEMI] = ACTIONS(113),
    [anon_sym_COMMA] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_RPAREN] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(113),
    [anon_sym_RBRACK] = ACTIONS(113),
    [anon_sym_COLON] = ACTIONS(113),
    [anon_sym_LBRACE] = ACTIONS(113),
    [anon_sym_RBRACE] = ACTIONS(113),
    [anon_sym_return] = ACTIONS(115),
    [anon_sym_let] = ACTIONS(115),
    [anon_sym_if] = ACTIONS(115),
    [anon_sym_BANG] = ACTIONS(115),
    [anon_sym_DASH] = ACTIONS(113),
    [anon_sym_EQ_EQ] = ACTIONS(113),
    [anon_sym_BANG_EQ] = ACTIONS(113),
    [anon_sym_GT_EQ] = ACTIONS(113),
    [anon_sym_LT_EQ] = ACTIONS(113),
    [anon_sym_GT] = ACTIONS(115),
    [anon_sym_LT] = ACTIONS(115),
    [anon_sym_STAR] = ACTIONS(113),
    [anon_sym_SLASH] = ACTIONS(113),
    [anon_sym_PLUS] = ACTIONS(113),
    [anon_sym_fn] = ACTIONS(115),
    [sym_integer] = ACTIONS(113),
    [anon_sym_DQUOTE] = ACTIONS(113),
    [sym_true] = ACTIONS(115),
    [sym_false] = ACTIONS(115),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(117),
    [sym_identifier] = ACTIONS(119),
    [anon_sym_SEMI] = ACTIONS(117),
    [anon_sym_COMMA] = ACTIONS(117),
    [anon_sym_LPAREN] = ACTIONS(117),
    [anon_sym_RPAREN] = ACTIONS(117),
    [anon_sym_LBRACK] = ACTIONS(117),
    [anon_sym_RBRACK] = ACTIONS(117),
    [anon_sym_COLON] = ACTIONS(117),
    [anon_sym_LBRACE] = ACTIONS(117),
    [anon_sym_RBRACE] = ACTIONS(117),
    [anon_sym_return] = ACTIONS(119),
    [anon_sym_let] = ACTIONS(119),
    [anon_sym_if] = ACTIONS(119),
    [anon_sym_BANG] = ACTIONS(119),
    [anon_sym_DASH] = ACTIONS(117),
    [anon_sym_EQ_EQ] = ACTIONS(117),
    [anon_sym_BANG_EQ] = ACTIONS(117),
    [anon_sym_GT_EQ] = ACTIONS(117),
    [anon_sym_LT_EQ] = ACTIONS(117),
    [anon_sym_GT] = ACTIONS(119),
    [anon_sym_LT] = ACTIONS(119),
    [anon_sym_STAR] = ACTIONS(117),
    [anon_sym_SLASH] = ACTIONS(117),
    [anon_sym_PLUS] = ACTIONS(117),
    [anon_sym_fn] = ACTIONS(119),
    [sym_integer] = ACTIONS(117),
    [anon_sym_DQUOTE] = ACTIONS(117),
    [sym_true] = ACTIONS(119),
    [sym_false] = ACTIONS(119),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(121),
    [sym_identifier] = ACTIONS(123),
    [anon_sym_SEMI] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(121),
    [anon_sym_LPAREN] = ACTIONS(121),
    [anon_sym_RPAREN] = ACTIONS(121),
    [anon_sym_LBRACK] = ACTIONS(121),
    [anon_sym_RBRACK] = ACTIONS(121),
    [anon_sym_COLON] = ACTIONS(121),
    [anon_sym_LBRACE] = ACTIONS(121),
    [anon_sym_RBRACE] = ACTIONS(121),
    [anon_sym_return] = ACTIONS(123),
    [anon_sym_let] = ACTIONS(123),
    [anon_sym_if] = ACTIONS(123),
    [anon_sym_BANG] = ACTIONS(123),
    [anon_sym_DASH] = ACTIONS(121),
    [anon_sym_EQ_EQ] = ACTIONS(121),
    [anon_sym_BANG_EQ] = ACTIONS(121),
    [anon_sym_GT_EQ] = ACTIONS(121),
    [anon_sym_LT_EQ] = ACTIONS(121),
    [anon_sym_GT] = ACTIONS(123),
    [anon_sym_LT] = ACTIONS(123),
    [anon_sym_STAR] = ACTIONS(121),
    [anon_sym_SLASH] = ACTIONS(121),
    [anon_sym_PLUS] = ACTIONS(121),
    [anon_sym_fn] = ACTIONS(123),
    [sym_integer] = ACTIONS(121),
    [anon_sym_DQUOTE] = ACTIONS(121),
    [sym_true] = ACTIONS(123),
    [sym_false] = ACTIONS(123),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(125),
    [sym_identifier] = ACTIONS(127),
    [anon_sym_SEMI] = ACTIONS(125),
    [anon_sym_COMMA] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(125),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(125),
    [anon_sym_COLON] = ACTIONS(125),
    [anon_sym_LBRACE] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_return] = ACTIONS(127),
    [anon_sym_let] = ACTIONS(127),
    [anon_sym_if] = ACTIONS(127),
    [anon_sym_BANG] = ACTIONS(127),
    [anon_sym_DASH] = ACTIONS(125),
    [anon_sym_EQ_EQ] = ACTIONS(125),
    [anon_sym_BANG_EQ] = ACTIONS(125),
    [anon_sym_GT_EQ] = ACTIONS(125),
    [anon_sym_LT_EQ] = ACTIONS(125),
    [anon_sym_GT] = ACTIONS(127),
    [anon_sym_LT] = ACTIONS(127),
    [anon_sym_STAR] = ACTIONS(125),
    [anon_sym_SLASH] = ACTIONS(125),
    [anon_sym_PLUS] = ACTIONS(125),
    [anon_sym_fn] = ACTIONS(127),
    [sym_integer] = ACTIONS(125),
    [anon_sym_DQUOTE] = ACTIONS(125),
    [sym_true] = ACTIONS(127),
    [sym_false] = ACTIONS(127),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(131),
    [sym_identifier] = ACTIONS(133),
    [anon_sym_SEMI] = ACTIONS(131),
    [anon_sym_COMMA] = ACTIONS(131),
    [anon_sym_LPAREN] = ACTIONS(131),
    [anon_sym_RPAREN] = ACTIONS(131),
    [anon_sym_LBRACK] = ACTIONS(131),
    [anon_sym_RBRACK] = ACTIONS(131),
    [anon_sym_COLON] = ACTIONS(131),
    [anon_sym_LBRACE] = ACTIONS(131),
    [anon_sym_RBRACE] = ACTIONS(131),
    [anon_sym_return] = ACTIONS(133),
    [anon_sym_let] = ACTIONS(133),
    [anon_sym_if] = ACTIONS(133),
    [anon_sym_BANG] = ACTIONS(133),
    [anon_sym_DASH] = ACTIONS(131),
    [anon_sym_EQ_EQ] = ACTIONS(131),
    [anon_sym_BANG_EQ] = ACTIONS(131),
    [anon_sym_GT_EQ] = ACTIONS(131),
    [anon_sym_LT_EQ] = ACTIONS(131),
    [anon_sym_GT] = ACTIONS(133),
    [anon_sym_LT] = ACTIONS(133),
    [anon_sym_STAR] = ACTIONS(131),
    [anon_sym_SLASH] = ACTIONS(131),
    [anon_sym_PLUS] = ACTIONS(131),
    [anon_sym_fn] = ACTIONS(133),
    [sym_integer] = ACTIONS(131),
    [anon_sym_DQUOTE] = ACTIONS(131),
    [sym_true] = ACTIONS(133),
    [sym_false] = ACTIONS(133),
  },
  [20] = {
    [ts_builtin_sym_end] = ACTIONS(125),
    [sym_identifier] = ACTIONS(127),
    [anon_sym_SEMI] = ACTIONS(125),
    [anon_sym_COMMA] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(125),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(125),
    [anon_sym_COLON] = ACTIONS(125),
    [anon_sym_LBRACE] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_return] = ACTIONS(127),
    [anon_sym_let] = ACTIONS(127),
    [anon_sym_if] = ACTIONS(127),
    [anon_sym_BANG] = ACTIONS(127),
    [anon_sym_DASH] = ACTIONS(135),
    [anon_sym_EQ_EQ] = ACTIONS(125),
    [anon_sym_BANG_EQ] = ACTIONS(125),
    [anon_sym_GT_EQ] = ACTIONS(125),
    [anon_sym_LT_EQ] = ACTIONS(125),
    [anon_sym_GT] = ACTIONS(127),
    [anon_sym_LT] = ACTIONS(127),
    [anon_sym_STAR] = ACTIONS(137),
    [anon_sym_SLASH] = ACTIONS(137),
    [anon_sym_PLUS] = ACTIONS(135),
    [anon_sym_fn] = ACTIONS(127),
    [sym_integer] = ACTIONS(125),
    [anon_sym_DQUOTE] = ACTIONS(125),
    [sym_true] = ACTIONS(127),
    [sym_false] = ACTIONS(127),
  },
  [21] = {
    [ts_builtin_sym_end] = ACTIONS(125),
    [sym_identifier] = ACTIONS(127),
    [anon_sym_SEMI] = ACTIONS(125),
    [anon_sym_COMMA] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(125),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(125),
    [anon_sym_COLON] = ACTIONS(125),
    [anon_sym_LBRACE] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_return] = ACTIONS(127),
    [anon_sym_let] = ACTIONS(127),
    [anon_sym_if] = ACTIONS(127),
    [anon_sym_BANG] = ACTIONS(127),
    [anon_sym_DASH] = ACTIONS(135),
    [anon_sym_EQ_EQ] = ACTIONS(125),
    [anon_sym_BANG_EQ] = ACTIONS(125),
    [anon_sym_GT_EQ] = ACTIONS(139),
    [anon_sym_LT_EQ] = ACTIONS(139),
    [anon_sym_GT] = ACTIONS(141),
    [anon_sym_LT] = ACTIONS(141),
    [anon_sym_STAR] = ACTIONS(137),
    [anon_sym_SLASH] = ACTIONS(137),
    [anon_sym_PLUS] = ACTIONS(135),
    [anon_sym_fn] = ACTIONS(127),
    [sym_integer] = ACTIONS(125),
    [anon_sym_DQUOTE] = ACTIONS(125),
    [sym_true] = ACTIONS(127),
    [sym_false] = ACTIONS(127),
  },
  [22] = {
    [ts_builtin_sym_end] = ACTIONS(143),
    [sym_identifier] = ACTIONS(145),
    [anon_sym_SEMI] = ACTIONS(143),
    [anon_sym_COMMA] = ACTIONS(143),
    [anon_sym_LPAREN] = ACTIONS(143),
    [anon_sym_RPAREN] = ACTIONS(143),
    [anon_sym_LBRACK] = ACTIONS(143),
    [anon_sym_RBRACK] = ACTIONS(143),
    [anon_sym_COLON] = ACTIONS(143),
    [anon_sym_LBRACE] = ACTIONS(143),
    [anon_sym_RBRACE] = ACTIONS(143),
    [anon_sym_return] = ACTIONS(145),
    [anon_sym_let] = ACTIONS(145),
    [anon_sym_if] = ACTIONS(145),
    [anon_sym_BANG] = ACTIONS(145),
    [anon_sym_DASH] = ACTIONS(143),
    [anon_sym_EQ_EQ] = ACTIONS(143),
    [anon_sym_BANG_EQ] = ACTIONS(143),
    [anon_sym_GT_EQ] = ACTIONS(143),
    [anon_sym_LT_EQ] = ACTIONS(143),
    [anon_sym_GT] = ACTIONS(145),
    [anon_sym_LT] = ACTIONS(145),
    [anon_sym_STAR] = ACTIONS(143),
    [anon_sym_SLASH] = ACTIONS(143),
    [anon_sym_PLUS] = ACTIONS(143),
    [anon_sym_fn] = ACTIONS(145),
    [sym_integer] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(143),
    [sym_true] = ACTIONS(145),
    [sym_false] = ACTIONS(145),
  },
  [23] = {
    [ts_builtin_sym_end] = ACTIONS(125),
    [sym_identifier] = ACTIONS(127),
    [anon_sym_SEMI] = ACTIONS(125),
    [anon_sym_COMMA] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(125),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(125),
    [anon_sym_COLON] = ACTIONS(125),
    [anon_sym_LBRACE] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_return] = ACTIONS(127),
    [anon_sym_let] = ACTIONS(127),
    [anon_sym_if] = ACTIONS(127),
    [anon_sym_BANG] = ACTIONS(127),
    [anon_sym_DASH] = ACTIONS(125),
    [anon_sym_EQ_EQ] = ACTIONS(125),
    [anon_sym_BANG_EQ] = ACTIONS(125),
    [anon_sym_GT_EQ] = ACTIONS(125),
    [anon_sym_LT_EQ] = ACTIONS(125),
    [anon_sym_GT] = ACTIONS(127),
    [anon_sym_LT] = ACTIONS(127),
    [anon_sym_STAR] = ACTIONS(137),
    [anon_sym_SLASH] = ACTIONS(137),
    [anon_sym_PLUS] = ACTIONS(125),
    [anon_sym_fn] = ACTIONS(127),
    [sym_integer] = ACTIONS(125),
    [anon_sym_DQUOTE] = ACTIONS(125),
    [sym_true] = ACTIONS(127),
    [sym_false] = ACTIONS(127),
  },
  [24] = {
    [ts_builtin_sym_end] = ACTIONS(147),
    [sym_identifier] = ACTIONS(149),
    [anon_sym_SEMI] = ACTIONS(147),
    [anon_sym_COMMA] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(147),
    [anon_sym_COLON] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_RBRACE] = ACTIONS(147),
    [anon_sym_return] = ACTIONS(149),
    [anon_sym_let] = ACTIONS(149),
    [anon_sym_if] = ACTIONS(149),
    [anon_sym_BANG] = ACTIONS(149),
    [anon_sym_DASH] = ACTIONS(147),
    [anon_sym_EQ_EQ] = ACTIONS(147),
    [anon_sym_BANG_EQ] = ACTIONS(147),
    [anon_sym_GT_EQ] = ACTIONS(147),
    [anon_sym_LT_EQ] = ACTIONS(147),
    [anon_sym_GT] = ACTIONS(149),
    [anon_sym_LT] = ACTIONS(149),
    [anon_sym_STAR] = ACTIONS(147),
    [anon_sym_SLASH] = ACTIONS(147),
    [anon_sym_PLUS] = ACTIONS(147),
    [anon_sym_fn] = ACTIONS(149),
    [sym_integer] = ACTIONS(147),
    [anon_sym_DQUOTE] = ACTIONS(147),
    [sym_true] = ACTIONS(149),
    [sym_false] = ACTIONS(149),
  },
  [25] = {
    [ts_builtin_sym_end] = ACTIONS(151),
    [sym_identifier] = ACTIONS(153),
    [anon_sym_SEMI] = ACTIONS(151),
    [anon_sym_COMMA] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(151),
    [anon_sym_RPAREN] = ACTIONS(151),
    [anon_sym_LBRACK] = ACTIONS(151),
    [anon_sym_RBRACK] = ACTIONS(151),
    [anon_sym_COLON] = ACTIONS(151),
    [anon_sym_LBRACE] = ACTIONS(151),
    [anon_sym_RBRACE] = ACTIONS(151),
    [anon_sym_return] = ACTIONS(153),
    [anon_sym_let] = ACTIONS(153),
    [anon_sym_if] = ACTIONS(153),
    [anon_sym_BANG] = ACTIONS(153),
    [anon_sym_DASH] = ACTIONS(151),
    [anon_sym_EQ_EQ] = ACTIONS(151),
    [anon_sym_BANG_EQ] = ACTIONS(151),
    [anon_sym_GT_EQ] = ACTIONS(151),
    [anon_sym_LT_EQ] = ACTIONS(151),
    [anon_sym_GT] = ACTIONS(153),
    [anon_sym_LT] = ACTIONS(153),
    [anon_sym_STAR] = ACTIONS(151),
    [anon_sym_SLASH] = ACTIONS(151),
    [anon_sym_PLUS] = ACTIONS(151),
    [anon_sym_fn] = ACTIONS(153),
    [sym_integer] = ACTIONS(151),
    [anon_sym_DQUOTE] = ACTIONS(151),
    [sym_true] = ACTIONS(153),
    [sym_false] = ACTIONS(153),
  },
  [26] = {
    [ts_builtin_sym_end] = ACTIONS(155),
    [sym_identifier] = ACTIONS(157),
    [anon_sym_SEMI] = ACTIONS(155),
    [anon_sym_COMMA] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [anon_sym_RBRACK] = ACTIONS(155),
    [anon_sym_COLON] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_RBRACE] = ACTIONS(155),
    [anon_sym_return] = ACTIONS(157),
    [anon_sym_let] = ACTIONS(157),
    [anon_sym_if] = ACTIONS(157),
    [anon_sym_BANG] = ACTIONS(157),
    [anon_sym_DASH] = ACTIONS(155),
    [anon_sym_EQ_EQ] = ACTIONS(155),
    [anon_sym_BANG_EQ] = ACTIONS(155),
    [anon_sym_GT_EQ] = ACTIONS(155),
    [anon_sym_LT_EQ] = ACTIONS(155),
    [anon_sym_GT] = ACTIONS(157),
    [anon_sym_LT] = ACTIONS(157),
    [anon_sym_STAR] = ACTIONS(155),
    [anon_sym_SLASH] = ACTIONS(155),
    [anon_sym_PLUS] = ACTIONS(155),
    [anon_sym_fn] = ACTIONS(157),
    [sym_integer] = ACTIONS(155),
    [anon_sym_DQUOTE] = ACTIONS(155),
    [sym_true] = ACTIONS(157),
    [sym_false] = ACTIONS(157),
  },
  [27] = {
    [ts_builtin_sym_end] = ACTIONS(159),
    [sym_identifier] = ACTIONS(161),
    [anon_sym_SEMI] = ACTIONS(159),
    [anon_sym_COMMA] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(159),
    [anon_sym_RPAREN] = ACTIONS(159),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(159),
    [anon_sym_COLON] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(159),
    [anon_sym_RBRACE] = ACTIONS(159),
    [anon_sym_return] = ACTIONS(161),
    [anon_sym_let] = ACTIONS(161),
    [anon_sym_if] = ACTIONS(161),
    [anon_sym_BANG] = ACTIONS(161),
    [anon_sym_DASH] = ACTIONS(159),
    [anon_sym_EQ_EQ] = ACTIONS(159),
    [anon_sym_BANG_EQ] = ACTIONS(159),
    [anon_sym_GT_EQ] = ACTIONS(159),
    [anon_sym_LT_EQ] = ACTIONS(159),
    [anon_sym_GT] = ACTIONS(161),
    [anon_sym_LT] = ACTIONS(161),
    [anon_sym_STAR] = ACTIONS(159),
    [anon_sym_SLASH] = ACTIONS(159),
    [anon_sym_PLUS] = ACTIONS(159),
    [anon_sym_fn] = ACTIONS(161),
    [sym_integer] = ACTIONS(159),
    [anon_sym_DQUOTE] = ACTIONS(159),
    [sym_true] = ACTIONS(161),
    [sym_false] = ACTIONS(161),
  },
  [28] = {
    [ts_builtin_sym_end] = ACTIONS(163),
    [sym_identifier] = ACTIONS(165),
    [anon_sym_SEMI] = ACTIONS(163),
    [anon_sym_COMMA] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(163),
    [anon_sym_RPAREN] = ACTIONS(163),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_RBRACK] = ACTIONS(163),
    [anon_sym_COLON] = ACTIONS(163),
    [anon_sym_LBRACE] = ACTIONS(163),
    [anon_sym_RBRACE] = ACTIONS(163),
    [anon_sym_return] = ACTIONS(165),
    [anon_sym_let] = ACTIONS(165),
    [anon_sym_if] = ACTIONS(165),
    [anon_sym_BANG] = ACTIONS(165),
    [anon_sym_DASH] = ACTIONS(163),
    [anon_sym_EQ_EQ] = ACTIONS(163),
    [anon_sym_BANG_EQ] = ACTIONS(163),
    [anon_sym_GT_EQ] = ACTIONS(163),
    [anon_sym_LT_EQ] = ACTIONS(163),
    [anon_sym_GT] = ACTIONS(165),
    [anon_sym_LT] = ACTIONS(165),
    [anon_sym_STAR] = ACTIONS(163),
    [anon_sym_SLASH] = ACTIONS(163),
    [anon_sym_PLUS] = ACTIONS(163),
    [anon_sym_fn] = ACTIONS(165),
    [sym_integer] = ACTIONS(163),
    [anon_sym_DQUOTE] = ACTIONS(163),
    [sym_true] = ACTIONS(165),
    [sym_false] = ACTIONS(165),
  },
  [29] = {
    [ts_builtin_sym_end] = ACTIONS(167),
    [sym_identifier] = ACTIONS(169),
    [anon_sym_SEMI] = ACTIONS(167),
    [anon_sym_COMMA] = ACTIONS(167),
    [anon_sym_LPAREN] = ACTIONS(167),
    [anon_sym_RPAREN] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(167),
    [anon_sym_RBRACK] = ACTIONS(167),
    [anon_sym_COLON] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_RBRACE] = ACTIONS(167),
    [anon_sym_return] = ACTIONS(169),
    [anon_sym_let] = ACTIONS(169),
    [anon_sym_if] = ACTIONS(169),
    [anon_sym_BANG] = ACTIONS(169),
    [anon_sym_DASH] = ACTIONS(167),
    [anon_sym_EQ_EQ] = ACTIONS(167),
    [anon_sym_BANG_EQ] = ACTIONS(167),
    [anon_sym_GT_EQ] = ACTIONS(167),
    [anon_sym_LT_EQ] = ACTIONS(167),
    [anon_sym_GT] = ACTIONS(169),
    [anon_sym_LT] = ACTIONS(169),
    [anon_sym_STAR] = ACTIONS(167),
    [anon_sym_SLASH] = ACTIONS(167),
    [anon_sym_PLUS] = ACTIONS(167),
    [anon_sym_fn] = ACTIONS(169),
    [sym_integer] = ACTIONS(167),
    [anon_sym_DQUOTE] = ACTIONS(167),
    [sym_true] = ACTIONS(169),
    [sym_false] = ACTIONS(169),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(177), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(175), 2,
      anon_sym_return,
      anon_sym_let,
    ACTIONS(179), 2,
      sym_true,
      sym_false,
    ACTIONS(171), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(36), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [58] = 5,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 1,
      anon_sym_EQ,
    STATE(11), 1,
      sym_arguments,
    ACTIONS(75), 10,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
    ACTIONS(73), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      sym_integer,
      anon_sym_DQUOTE,
  [97] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    ACTIONS(185), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    STATE(74), 1,
      sym__parameters,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(187), 2,
      sym_true,
      sym_false,
    STATE(54), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [152] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_integer,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym_elements,
    STATE(76), 1,
      sym__parameters,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(187), 2,
      sym_true,
      sym_false,
    STATE(54), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [207] = 8,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(191), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(193), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [250] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    STATE(64), 1,
      sym_pair,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(201), 2,
      sym_true,
      sym_false,
    STATE(59), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [305] = 8,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(203), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(205), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [348] = 8,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(207), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(209), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [391] = 8,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(211), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(213), 8,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_BANG,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
  [434] = 14,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_integer,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_elements,
    STATE(75), 1,
      sym__parameters,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(187), 2,
      sym_true,
      sym_false,
    STATE(54), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [489] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(199), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    STATE(68), 1,
      sym_pair,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(201), 2,
      sym_true,
      sym_false,
    STATE(59), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [541] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(217), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(219), 2,
      sym_true,
      sym_false,
    STATE(20), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [590] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(221), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(223), 2,
      sym_true,
      sym_false,
    STATE(34), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [639] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(225), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(227), 2,
      sym_true,
      sym_false,
    STATE(18), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [688] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(229), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(231), 2,
      sym_true,
      sym_false,
    STATE(21), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [737] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(233), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(235), 2,
      sym_true,
      sym_false,
    STATE(55), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [786] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(237), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(239), 2,
      sym_true,
      sym_false,
    STATE(27), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [835] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(241), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(243), 2,
      sym_true,
      sym_false,
    STATE(23), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [884] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(245), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(247), 2,
      sym_true,
      sym_false,
    STATE(57), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [933] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(249), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(251), 2,
      sym_true,
      sym_false,
    STATE(56), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [982] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(253), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(255), 2,
      sym_true,
      sym_false,
    STATE(38), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [1031] = 12,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(257), 1,
      sym_integer,
    STATE(16), 1,
      sym_elements,
    ACTIONS(19), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(259), 2,
      sym_true,
      sym_false,
    STATE(58), 11,
      sym__expression,
      sym_if_expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_grouped_expression,
      sym_call,
      sym_index_expression,
      sym_function_literal,
      sym_string,
      sym_array,
      sym_hash,
  [1080] = 3,
    ACTIONS(265), 1,
      anon_sym_SEMI,
    ACTIONS(263), 7,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
    ACTIONS(261), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer,
      anon_sym_DQUOTE,
  [1104] = 2,
    ACTIONS(269), 7,
      anon_sym_return,
      anon_sym_let,
      anon_sym_if,
      anon_sym_fn,
      sym_identifier,
      sym_true,
      sym_false,
    ACTIONS(267), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DASH,
      sym_integer,
      anon_sym_DQUOTE,
  [1125] = 9,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym__parameters_repeat1,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(273), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1159] = 7,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(275), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1188] = 7,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1216] = 7,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1243] = 7,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1270] = 7,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(283), 1,
      anon_sym_COLON,
    ACTIONS(135), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(137), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(139), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(141), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1297] = 3,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym__parameters_repeat1,
    ACTIONS(275), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1308] = 3,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym__parameters_repeat1,
    ACTIONS(288), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1319] = 3,
    ACTIONS(290), 1,
      anon_sym_DQUOTE,
    ACTIONS(292), 1,
      aux_sym_string_token1,
    STATE(66), 1,
      aux_sym_string_repeat1,
  [1329] = 3,
    ACTIONS(294), 1,
      anon_sym_DQUOTE,
    ACTIONS(296), 1,
      aux_sym_string_token1,
    STATE(63), 1,
      aux_sym_string_repeat1,
  [1339] = 3,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_hash_repeat1,
  [1349] = 3,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    ACTIONS(306), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_hash_repeat1,
  [1359] = 3,
    ACTIONS(308), 1,
      anon_sym_DQUOTE,
    ACTIONS(310), 1,
      aux_sym_string_token1,
    STATE(63), 1,
      aux_sym_string_repeat1,
  [1369] = 3,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_hash_repeat1,
  [1379] = 1,
    ACTIONS(306), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1384] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_block_statement,
  [1391] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_block_statement,
  [1398] = 2,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block_statement,
  [1405] = 2,
    ACTIONS(316), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym_parameters,
  [1412] = 2,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      sym_grouped_expression,
  [1419] = 1,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
  [1423] = 1,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
  [1427] = 1,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
  [1431] = 1,
    ACTIONS(324), 1,
      anon_sym_EQ,
  [1435] = 1,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
  [1439] = 1,
    ACTIONS(328), 1,
      ts_builtin_sym_end,
  [1443] = 1,
    ACTIONS(330), 1,
      anon_sym_LBRACE,
  [1447] = 1,
    ACTIONS(332), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(30)] = 0,
  [SMALL_STATE(31)] = 58,
  [SMALL_STATE(32)] = 97,
  [SMALL_STATE(33)] = 152,
  [SMALL_STATE(34)] = 207,
  [SMALL_STATE(35)] = 250,
  [SMALL_STATE(36)] = 305,
  [SMALL_STATE(37)] = 348,
  [SMALL_STATE(38)] = 391,
  [SMALL_STATE(39)] = 434,
  [SMALL_STATE(40)] = 489,
  [SMALL_STATE(41)] = 541,
  [SMALL_STATE(42)] = 590,
  [SMALL_STATE(43)] = 639,
  [SMALL_STATE(44)] = 688,
  [SMALL_STATE(45)] = 737,
  [SMALL_STATE(46)] = 786,
  [SMALL_STATE(47)] = 835,
  [SMALL_STATE(48)] = 884,
  [SMALL_STATE(49)] = 933,
  [SMALL_STATE(50)] = 982,
  [SMALL_STATE(51)] = 1031,
  [SMALL_STATE(52)] = 1080,
  [SMALL_STATE(53)] = 1104,
  [SMALL_STATE(54)] = 1125,
  [SMALL_STATE(55)] = 1159,
  [SMALL_STATE(56)] = 1188,
  [SMALL_STATE(57)] = 1216,
  [SMALL_STATE(58)] = 1243,
  [SMALL_STATE(59)] = 1270,
  [SMALL_STATE(60)] = 1297,
  [SMALL_STATE(61)] = 1308,
  [SMALL_STATE(62)] = 1319,
  [SMALL_STATE(63)] = 1329,
  [SMALL_STATE(64)] = 1339,
  [SMALL_STATE(65)] = 1349,
  [SMALL_STATE(66)] = 1359,
  [SMALL_STATE(67)] = 1369,
  [SMALL_STATE(68)] = 1379,
  [SMALL_STATE(69)] = 1384,
  [SMALL_STATE(70)] = 1391,
  [SMALL_STATE(71)] = 1398,
  [SMALL_STATE(72)] = 1405,
  [SMALL_STATE(73)] = 1412,
  [SMALL_STATE(74)] = 1419,
  [SMALL_STATE(75)] = 1423,
  [SMALL_STATE(76)] = 1427,
  [SMALL_STATE(77)] = 1431,
  [SMALL_STATE(78)] = 1435,
  [SMALL_STATE(79)] = 1439,
  [SMALL_STATE(80)] = 1443,
  [SMALL_STATE(81)] = 1447,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(51),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(39),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(35),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(30),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(81),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(73),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(46),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(72),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(37),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(62),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(37),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3, .production_id = 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3, .production_id = 4),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 3, .production_id = 5),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 3, .production_id = 5),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expression, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expression, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elements, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elements, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 1, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 1, .production_id = 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expression, 3, .production_id = 7),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_infix_expression, 3, .production_id = 7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elements, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elements, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expression, 2, .production_id = 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expression, 2, .production_id = 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, .production_id = 11),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, .production_id = 11),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_expression, 4, .production_id = 10),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index_expression, 4, .production_id = 10),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 6),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, .production_id = 6),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, .production_id = 9),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, .production_id = 9),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statements, 1),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 2),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statements, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 1),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 8),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2), SHIFT_REPEAT(45),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(63),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2), SHIFT_REPEAT(40),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [328] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
